### PR TITLE
Update 10-unattended.sh

### PR DESCRIPTION
**Pull request by stephenseiber**
add disk selection for formating drive

### CODE REVIEW

**Comment by stephenseiber** [comment]
didn't see the zram so remove unnecessary swap file

**Comment by santigo-zero** [comment]
Hi Stephen, I'm spotting a problem with your pull request, I haven't tested the changes just yet, but in [this line](https://github.com/santigo-zero/csjarchlinux/blob/8143131678ae429043a140e432966de4fc6a2248/10-unattended.sh#L192) the three bootloader entries are still pointing to /dev/nvme0n1p2 so the bootloader will never find the disk that you have chosen to use, since the UUID will be wrong, I'm still new to git and github, so I don't know how to fix the variable before doing the merge, do you know how to fix that?

**Comment by stephenseiber** [comment]
I have updated the pull request to fix that normally you would click commits the click the latest one at the bottom click the three dots that appear at the top right of the code block and edit… then make corrections then and hit commit on the bottom

**Comment by stephenseiber** [comment]
Did have a question about intel_agp i915 and the backlight code???  Is this more performant then with mesa??? Aside from the backlight code I’m pretty sure the rest is already included in mesa by default

**Comment by stephenseiber** [comment]
sry in my still waking up state i tried to put the boot partition into the arch.conf instead of root last commit fixes that

**Pull request merged**
