### PR TITLE
Update 10-unattended.sh

### LINKED ISSUE #11: weirdness with password promt
this is what happens

Enter host name, or press enter to use defaults:
Enter user password, or press enter to use defaults: Enter root password, or press enter to use defaults: 
 expectation
Enter host name, or press enter to use defaults:
Enter user password, or press enter to use defaults: 
Enter root password, or press enter to use defaults:

### PR DESCRIPTION
**Pull request by stephenseiber**
automatic snapshots also put apparmor into here
adds a line break "basically enter key" after asking each question in the begining which fixes #11 
added reboot question to bottom of script if yes reboots
#2 this is part of fixing this issue i havent yet figured out how to make it bootable from systemd-boot
fixed issue santigo-zero#5
made more automated
instead of asking for drive password to encryption or open at encryption creation and opening ask for it with other variables

snapper-gui-git is in aur for gui for managing snapshots

your free to check out my installer which is based off urs
https://github.com/stephenseiber/arch

### CODE REVIEW

**Comment by stephenseiber** [comment]
your free to check out my installer which is based off urs

**Comment by stephenseiber** [comment]
#2 this is part of fixing this issue i havent yet figured out how to make it bootable from systemd-boot

**Comment by santigo-zero** [comment]
You are adding snapshot support? In that case we would need to also add a subvolume for .snapshots, and offer a solution for systemd-boot, I'll not merge this right now since I want to make sure we can boot from those snapshots.

**Comment by stephenseiber** [comment]
> You are adding snapshot support? In that case we would need to also add a subvolume for .snapshots 
yes this can be done but not necessarily beneficial… and each sub volume has its own .snapshots folder

**Comment by stephenseiber** [comment]
> You are adding snapshot support? In that case we would need to also add a subvolume for .snapshots

this doesnt appear to be necessary because snapshots are their own subvolume...

**Comment by santigo-zero** [comment]
This looks pretty good to me, the only thing that I'm not really liking is that there's no verification for the passwords for user, root and encryption, we just echo once. So tomorrow if I have time I'll add a verification just to make sure users don't install Arch without being able to enter to it, yes, this has happened to me, that's why encryption wasn't using read and echo, it was the command only. Can I push to this pull request? Or do I need to first merge this and then push it the normal way?

**Comment by stephenseiber** [comment]
> This looks pretty good to me, the only thing that I'm not really liking is that there's no verification for the passwords for user, root and encryption, we just echo once. So tomorrow if I have time I'll add a verification just to make sure users don't install Arch without being able to enter to it, yes, this has happened to me, that's why encryption wasn't using read and echo, it was the command only. 
Can I push to this pull request? Or do I need to first merge this and then push it the normal way? i dont know if you can push to this request

**Pull request merged**
